package ec.ups.edu.eva.EVA_Barzallo_Xavier_CLI;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.0
 * 2022-02-01T12:37:12.861-05:00
 * Generated source version: 3.5.0
 *
 */
@WebService(targetNamespace = "http://bean.eva.edu.ups.ec/", name = "ObrasServiceSOAP")
@XmlSeeAlso({ObjectFactory.class})
public interface ObrasServiceSOAP {

    @WebMethod
    @RequestWrapper(localName = "getContactos", targetNamespace = "http://bean.eva.edu.ups.ec/", className = "ec.ups.edu.eva.EVA_Barzallo_Xavier_CLI.GetContactos")
    @ResponseWrapper(localName = "getContactosResponse", targetNamespace = "http://bean.eva.edu.ups.ec/", className = "ec.ups.edu.eva.EVA_Barzallo_Xavier_CLI.GetContactosResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ec.ups.edu.eva.EVA_Barzallo_Xavier_CLI.Obra> getContactos()
;

    @WebMethod
    @RequestWrapper(localName = "crearContacto", targetNamespace = "http://bean.eva.edu.ups.ec/", className = "ec.ups.edu.eva.EVA_Barzallo_Xavier_CLI.CrearContacto")
    @ResponseWrapper(localName = "crearContactoResponse", targetNamespace = "http://bean.eva.edu.ups.ec/", className = "ec.ups.edu.eva.EVA_Barzallo_Xavier_CLI.CrearContactoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String crearContacto(

        @WebParam(name = "arg0", targetNamespace = "")
        ec.ups.edu.eva.EVA_Barzallo_Xavier_CLI.Obra arg0
    );
}
