
package ec.ups.edu.eva.EVA_Barzallo_Xavier_CLI;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.0
 * 2022-02-01T12:37:12.809-05:00
 * Generated source version: 3.5.0
 *
 */
public final class ObrasServiceSOAP_ObrasServiceSOAPPort_Client {

    private static final QName SERVICE_NAME = new QName("http://bean.eva.edu.ups.ec/", "ObrasServiceSOAPService");

    private ObrasServiceSOAP_ObrasServiceSOAPPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ObrasServiceSOAPService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        ObrasServiceSOAPService ss = new ObrasServiceSOAPService(wsdlURL, SERVICE_NAME);
        ObrasServiceSOAP port = ss.getObrasServiceSOAPPort();

        {
        System.out.println("Invoking getContactos...");
        java.util.List<ec.ups.edu.eva.EVA_Barzallo_Xavier_CLI.Obra> _getContactos__return = port.getContactos();
        System.out.println("getContactos.result=" + _getContactos__return);


        }
        {
        System.out.println("Invoking crearContacto...");
        ec.ups.edu.eva.EVA_Barzallo_Xavier_CLI.Obra _crearContacto_arg0 = null;
        
       
        
        
        java.lang.String _crearContacto__return = port.crearContacto(_crearContacto_arg0);
        System.out.println("crearContacto.result=" + _crearContacto__return);


        }

        System.exit(0);
    }

}
